import os

MODEL = 'model'
MODEL_DIR = 'hanzi_recog_model'
#MODEL_DIR = 'hanzi_recog_model - Copy97.65'
TF_LITE_MODEL = 'converted_model.tflite'
LOG_DIR = 'logs'
ROOT_LOG_DIR = os.path.join(os.curdir, LOG_DIR)
CHECKPOINT = 'checkpoint'
CHECKPOINT_DIR =  os.path.join(os.curdir, CHECKPOINT)
FIRST_TOP_CHARACTERS = 3
BATCH_SIZE = 250 #250 #170 # 490
VALIDATION_FREQ = 1 #150

# ROOT='C:\Users\I-Tang\DATA\DEV\TENSORFLOW\OnlineHanziRecognizer_tf'
ROOT = 'C:\DEV\TENSORFLOW\OnlineHanziRecognizer_tf2'
#ROOT = '/home/ithiu/DATA/DEV/TENSORFLOW/OnlineHanziRecognizer_tf2'

DATA_ROOT_DIR = 'E:\CHINESE_CHARACTER_RECOGNIZER\CASIA\TEMP_GENERATED_DATASET'
#DATA_ROOT_DIR = 'E:\CHINESE_CHARACTER_RECOGNIZER\CASIA\TEMP_GENERATED_DATASET'

#DATA_ROOT_DIR = '/media/ithiu/TOSH_RED_4T/CHINESE_CHARACTER_RECOGNIZER/CASIA/TEMP_GENERATED_DATASET'
DATA_ROOT_DIR2 = 'E:\CHINESE_CHARACTER_RECOGNIZER\CASIA\TEMP_GENERATED_DATASET2'

DATA_TRAINING = DATA_ROOT_DIR + '/training'
DATA_VALIDATION = DATA_ROOT_DIR + '/validation'
DATA_TEST = DATA_ROOT_DIR + '/test'

DATA_TRAINING_LIGHT = DATA_ROOT_DIR + '/training_light'
DATA_VALIDATION_LIGHT = DATA_ROOT_DIR + '/validation_light'
DATA_TEST_LIGHT = DATA_ROOT_DIR + '/test_light'

DATA_TRAINING2 = DATA_ROOT_DIR2 + '/training'
DATA_VALIDATION2 = DATA_ROOT_DIR2 + '/validation'
CHARSET_SIZE = 3755
IMAGE_SIZE = 64